# -*- coding: utf-8 -*-
"""Run the Zartman & Doe (1981) Version I model.

Prints the 11-cycle growth history, compares it against Table IV of
Zartman & Doe (1981) and writes ``outputs/results/version1_comparison.csv``.
"""
import os

import numpy as np
import pandas as pd

from plumbotectonics.version1 import run

RESERVOIRS = ("mantle", "orogene", "upper", "lower")
RATIOS = ("206/204", "207/204", "208/204")
COLUMNS = ["t_Ga", "reservoir", "ratio", "model", "literature", "abs_diff", "rel_error_pct"]

# Zartman & Doe (1981), Table IV: lead-isotopic composition of the reservoir
# growth curves generated by version I.  One tuple per cycle, oldest first,
# holding (206Pb/204Pb, 207Pb/204Pb, 208Pb/204Pb).
# Two orogene / 208Pb cells are corrected for obvious scan damage; see
# docs/validation.md section 2.
TABLE_IV = {
    "mantle": [
        (10.36, 12.12, 30.55), (11.36, 13.21, 31.34), (12.30, 13.94, 32.11),
        (13.19, 14.44, 32.86), (14.02, 14.78, 33.59), (14.80, 15.00, 34.30),
        (15.54, 15.15, 35.00), (16.23, 15.26, 35.69), (16.88, 15.33, 36.37),
        (17.50, 15.38, 37.03), (18.08, 15.42, 37.68),
    ],
    "orogene": [
        (10.36, 12.12, 30.55), (11.42, 13.27, 31.40), (12.47, 14.09, 32.30),
        (13.50, 14.67, 33.20), (14.47, 15.06, 34.11), (15.35, 15.29, 34.95),
        (16.17, 15.44, 35.77), (16.92, 15.53, 36.56), (17.62, 15.58, 37.34),
        (18.27, 15.61, 38.09), (18.88, 15.63, 38.82),
    ],
    "upper": [
        (10.36, 12.12, 30.55), (11.61, 13.48, 31.57), (12.69, 14.29, 32.46),
        (13.72, 14.83, 33.35), (14.70, 15.20, 34.23), (15.64, 15.44, 35.10),
        (16.51, 15.59, 35.94), (17.30, 15.67, 36.76), (18.04, 15.71, 37.55),
        (18.71, 15.73, 38.32), (19.33, 15.73, 39.06),
    ],
    "lower": [
        (10.36, 12.12, 30.55), (10.98, 12.79, 31.41), (11.76, 13.46, 32.24),
        (12.52, 13.95, 33.06), (13.27, 14.33, 33.89), (14.00, 14.61, 34.70),
        (14.72, 14.83, 35.51), (15.40, 15.00, 36.29), (16.06, 15.13, 37.06),
        (16.69, 15.22, 37.82), (17.29, 15.30, 38.56),
    ],
}


def _finalise(frame):
    """Add absolute and percentage differences against the literature column."""
    model = frame["model"].to_numpy()
    literature = frame["literature"].to_numpy()
    frame["abs_diff"] = model - literature
    frame["rel_error_pct"] = np.abs((model - literature) / literature) * 100.0
    return frame[COLUMNS]


def comparison_frame(history):
    """One row per (cycle, reservoir, ratio), model next to Table IV."""
    records = []
    for index, entry in enumerate(history):
        for reservoir in RESERVOIRS:
            data = entry.get(reservoir)
            if not data:
                continue
            for ratio, literature in zip(RATIOS, TABLE_IV[reservoir][index]):
                records.append({
                    "t_Ga": entry["t"],
                    "reservoir": reservoir,
                    "ratio": ratio,
                    "model": data[ratio],
                    "literature": literature,
                })
    return _finalise(pd.DataFrame(records))


def _fmt(d):
    if not d:
        return "-"
    return f"{d['206/204']:.2f}/{d['207/204']:.2f}/{d['208/204']:.2f}"


def main():
    history, _, _, _ = run()

    print("t (Ga)  Mantle              Orogene             Upper               Lower")
    for entry in history:
        print(
            f"{entry['t']:.1f}  {_fmt(entry['mantle']):<19} {_fmt(entry['orogene']):<19} "
            f"{_fmt(entry['upper']):<19} {_fmt(entry['lower'])}"
        )

    frame = comparison_frame(history)
    frame["model"] = frame["model"].round(6)
    frame["literature"] = frame["literature"].round(6)
    frame["abs_diff"] = frame["abs_diff"].round(6)
    frame["rel_error_pct"] = frame["rel_error_pct"].round(4)

    residual = frame["model"].to_numpy() - frame["literature"].to_numpy()
    print()
    print(frame.to_string(index=False))
    print(
        f"\nrows = {len(frame)}   max |abs_diff| = {np.max(np.abs(residual)):.6f}"
        f"   max |rel_error_pct| = {np.max(np.abs(frame['rel_error_pct'].to_numpy())):.4f} %"
        f"   RMSE = {np.sqrt(np.mean(residual ** 2)):.6f}"
    )

    out = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "outputs", "results", "version1_comparison.csv")
    )
    os.makedirs(os.path.dirname(out), exist_ok=True)
    frame.to_csv(out, index=False, encoding="utf-8-sig")
    print(f"Saved: {out}")


if __name__ == "__main__":
    main()
